#!/bin/sh
#
# Converts a WAV audio file to an Audiokinetic WEM file suitable for
# Rocksmith 2014
#
# Usage:
#     wav2wem FILE...
#
SCRIPTPATH=$(readlink -f "$0")
THISPATH=$(cd "$(dirname "$SCRIPTPATH")"; pwd)

for var in "$@"
do
    BASENAME=$(basename "$var")
    BASENAME="${BASENAME%.*}"

    tar -zxf "$THISPATH/Template.tar.gz"
    cp "$1" Template/Originals/SFX/song.wav

    cd Template
    "$THISPATH/WwiseCLI" Template.wproj -GenerateSoundBanks
    cd ..

    mv Template/.cache/Windows/SFX/*.wem "$BASENAME.wem"
    #mv Template/GeneratedSoundBanks/Windows/RS_SOUNDBANK.bnk "$BASENAME.bnk"
    rm -fr Template
done
